$(document).ready(function(){
    $("#basic-info").click(function(){
        $(".basic-info").show();
        $(".documents").hide();
        $(".facilities").hide();
        $(".registration").hide();
        $(".location").hide();
        $(".necessary").hide();
        $(".counselling").hide();

    });

    $("#documents").click(function(){
        $(".basic-info").hide();
        $(".documents").show();
        $(".facilities").hide();
        $(".registration").hide();
        $(".location").hide();
        $(".necessary").hide();
        $(".counselling").hide();
    });
    $("#facilities").click(function(){
        $(".basic-info").hide();
        $(".documents").hide();
        $(".facilities").show();
        $(".registration").hide();
        $(".location").hide();
        $(".necessary").hide();
        $(".counselling").hide();
    });
    $("#registration").click(function(){
        $(".basic-info").hide();
        $(".documents").hide();
        $(".facilities").hide();
        $(".registration").show();
        $(".location").hide();
        $(".necessary").hide();
        $(".counselling").hide();
    });
    $("#location").click(function(){
        $(".basic-info").hide();
        $(".documents").hide();
        $(".facilities").hide();
        $(".registration").hide();
        $(".location").show();
        $(".necessary").hide();
        $(".counselling").hide();
    });
    $("#necessary").click(function(){
        $(".basic-info").hide();
        $(".documents").hide();
        $(".facilities").hide();
        $(".registration").hide();
        $(".location").hide();
        $(".necessary").show();
        $(".counselling").hide();
    });
    $("#counselling").click(function(){
        $(".basic-info").hide();
        $(".documents").hide();
        $(".facilities").hide();
        $(".registration").hide();
        $(".location").hide();
        $(".necessary").hide();
        $(".counselling").show();
    });

});